### ISSUE TITLE
HDP2.5 Sandbox docker image: default password doesn't work.

### ISSUE THREAD

**Issue by jamesatapivista** [hortonworks/data-tutorials#207] opened 2017-02-20 16:20 UTC
**Tutorial Name**: hortonworks-sandbox-hdp2.5-guide/install_guide_docker
**HDP Version are you Running**: HDP2.5 sandbox, docker image
**Applicable HDP Components**: Hortonworks Docker Sandbox

**Link to tutorial**(Hortonworks or GitHub website):
https://github.com/hortonworks/tutorials/blob/hdp-2.5/tutorials/hortonworks/hortonworks-sandbox-hdp2.5-guide/install_guide_docker.md

https://github.com/hortonworks/tutorials/blob/hdp/tutorials/hortonworks/learning-the-ropes-of-the-hortonworks-sandbox/tutorial.md

### Detailed Description of Issue:
- Launch the HDP2.5 sandbox docker image.
- Go to http://localhost:8888/#
- "Launch Dashboard"
- Enter username "root", password "hadoop"
- Result: "Unable to sign in. Invalid username/password combination."

Default username and password are incorrect. The "learning-the-ropes-of-the-hortonworks-sandbox/tutorial.md" says to use username "root" and password "hadoop". Neither are correct. If credentials are different for the docker image, "hortonworks-sandbox-hdp2.5-guide/install_guide_docker.md" doesn't contain username/password info specific to the image.

To be able to log in I had to `docker exec -it sandbox bash` then `ambari-admin-password-reset` and use username "admin" with the new password, before could log into the sandbox dashboard. I have validated by `docker rm`ing the container and starting over.

### Proposed Fix:
@Jaraxal could you direct me to maintainer for the Dockerfile of the Hortonworks Sandbox. I know my issue should be directed there but I have not been able to find that repo. I don't have the expertise to fix this issue. I just know the default username/password should be fixed.

**Comment by Jaraxal** [comment] 2017-02-20 16:28
@jamesatapivista 
The username **root** and the password **hadoop** is for accessing the Sandbox via SSH.  When you use "Launch Dashboard", you are loging into the Ambari admin interface.  The login/password you should use is **raj_ops** or **maria_dev**.  As you discovered, you can enable the admin account using **ambari-admin-password-reset**.

So the issue is the tutorial should be updated to reflect the proper username and password for clarity.

**Comment by jamesatapivista** [comment] 2017-02-20 16:39
@Jaraxal
My bad for not looking further down the tutorial, I see the ambari admin interface instructions further down the tutorial.

I definitely think the tutorial should have that username and password info sooner. As you can see in the tutorial, step 1.3 , it suggests you go to the ambari admin interface immediately, then shows no username/password until much later, in step 2.0 . The first credentials you see are for the SSH connection in step 1.4 .

Would you like me to issue a pull request to add login credentials as early as step 1.3 or remove step 1.3 in favor of the dashboard being introduced in step 2.0 ? Or I can leave that up do you?

**Comment by Jaraxal** [comment] 2017-02-20 16:57
@jamesatapivista 
I agree the tutorial can cause confusion.  I've submitted a pull request to help clarify.

**Comment by jamesatapivista** [comment] 2017-02-20 16:59
@Jaraxal
Thanks for that. The commit/pull looks great. I closed the issue. Should I have waited until the pull request is resolved?

**Comment by jamesatapivista** [comment] 2017-02-20 17:01
@Jaraxal 
Thanks for all the help. Thanks for helping a novice out.

**Comment by Jaraxal** [comment] 2017-02-20 17:05
@jamesatapivista 
Anytime!

**Comment by orendain** [comment] 2017-03-27 19:49
Merged in changes proposed by the pull request referencing this issue :)

https://github.com/hortonworks/data-tutorials/pull/208

**Closed by orendain** 2017-03-27 19:49 UTC
